import localFont from "next/font/local";
import "./globals.css";
import Header from '@/Components/Header';
import Nav from '@/Components/Nav';
import { Routes, Route } from 'react-router-dom';
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
		<head>
		 <Header>
		</Header>
		</head>
		<body className={`${geistSans.variable} ${geistMono.variable}`}>
			<Nav></Nav>
        {children}
      </body>
    </html>
  );
}
